# Generated by Django 4.0.6 on 2022-07-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_produto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=45),
        ),
    ]
