# Generated by Django 4.0.6 on 2022-10-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(help_text='olá', max_length=18),
        ),
    ]
