# Generated by Django 4.0.6 on 2022-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_venda_cliente_alter_venda_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('DN', 'Dinheiro'), ('CC', 'Cartão de crédito'), ('CD', 'Cartão de débito'), ('OT', 'Outros')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='venda',
            name='observacoes',
            field=models.TextField(blank=True, default='Nenhuma'),
        ),
    ]
