# Generated by Django 4.0.6 on 2022-09-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=65)),
                ('cor', models.CharField(max_length=35)),
                ('memoria', models.IntegerField(choices=[(2, '2Gb RAM'), (4, '4Gb RAM'), (6, '6Gb RAM'), (8, '8Gb RAM'), (12, '12Gb RAM')])),
                ('armazenamento', models.IntegerField(choices=[(16, '16Gb ROM'), (32, '32Gb ROM'), (64, '64Gb ROM'), (128, '128Gb ROM'), (256, '256Gb ROM'), (512, '512Gb ROM')])),
                ('codigo_produto', models.CharField(blank=True, max_length=65)),
                ('valor_compra', models.FloatField()),
                ('status', models.CharField(choices=[('ET', 'Estoque'), ('VD', 'Vendido')], default='ET', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
