# Generated by Django 4.0.6 on 2022-09-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='status',
        ),
        migrations.AddField(
            model_name='produto',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
