# Generated by Django 4.0.6 on 2022-10-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_produto_status_produto_vendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_produto',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
