# Generated by Django 4.0.6 on 2022-07-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_produto_armazenamento_alter_produto_memoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='', max_length=45),
        ),
    ]
