# Generated by Django 4.0.6 on 2022-10-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_produto_codigo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_produto',
            field=models.CharField(blank=True, max_length=6, verbose_name='Código do produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_compra',
            field=models.FloatField(verbose_name='Valor da compra'),
        ),
    ]
