# Generated by Django 4.0.6 on 2022-08-01 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_produto_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='armazenamento',
            field=models.IntegerField(choices=[(16, '16Gb ROM'), (32, '32Gb ROM'), (64, '64Gb ROM'), (128, '128Gb ROM'), (256, '256Gb ROM'), (512, '512Gb ROM')]),
        ),
    ]
